ROOTPATH: /Users/yijingch/Documents/GITHUB/invisible-public/
ROOTPATH2: /Users/yijingch/Documents/GITHUB/dd-full/
DATAPATH: /Users/yijingch/Documents/GITHUB/dd-full/data/
DATAPATH2: /Users/yijingch/Documents/GITHUB/collect-youtube-content/data/
INDEXPATH: /Users/yijingch/Documents/GITHUB/dd-full/index/

START: 2018-05-01 00:00:00
END: 2023-05-01 00:00:00